name: mcddpm
channels:
  - pytorch
  - nvidia
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex
  - _openmp_mutex
  - aiofiles
  - aiosqlite
  - argon2-cffi
  - argon2-cffi-bindings
  - arrow
  - asttokens
  - babel
  - backcall
  - beautifulsoup4
  - blas
  - bleach
  - brotli-python
  - brotlipy
  - bzip2
  - ca-certificates
  - cached-property
  - cached_property
  - cffi
  - charset-normalizer
  - cryptography
  - cuda-cudart
  - cuda-cupti
  - cuda-libraries
  - cuda-nvrtc
  - cuda-nvtx
  - cuda-runtime
  - cudatoolkit
  - dbus
  - decorator
  - defusedxml
  - entrypoints
  - exceptiongroup
  - executing
  - expat
  - ffmpeg
  - flit-core
  - fontconfig
  - fqdn
  - freetype
  - giflib
  - glib
  - gmp
  - gmpy2
  - gnutls
  - gst-plugins-base
  - gstreamer
  - icu
  - idna
  - importlib-metadata
  - importlib_metadata
  - importlib_resources
  - intel-openmp
  - ipython_genutils
  - isoduration
  - jedi
  - jpeg
  - json5
  - jsonpointer
  - jsonschema-specifications
  - jsonschema-with-format-nongpl
  - jupyter
  - jupyter_client
  - jupyter_events
  - jupyter_server_fileid
  - jupyter_server_ydoc
  - jupyter_ydoc
  - jupyterlab_server
  - jupyterlab_widgets
  - krb5
  - lame
  - lcms2
  - ld_impl_linux-64
  - lerc
  - libclang
  - libcublas
  - libcufft
  - libcufile
  - libcurand
  - libcusolver
  - libcusparse
  - libdeflate
  - libedit
  - libevent
  - libffi
  - libgcc-ng
  - libgomp
  - libiconv
  - libidn2
  - libjpeg-turbo
  - libllvm10
  - libnpp
  - libnvjpeg
  - libpng
  - libpq
  - libsodium
  - libstdcxx-ng
  - libtasn1
  - libtiff
  - libunistring
  - libuuid
  - libwebp
  - libwebp-base
  - libxcb
  - libxkbcommon
  - libxml2
  - libxslt
  - llvm-openmp
  - lxml
  - lz4-c
  - matplotlib-inline
  - mistune
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - mpc
  - mpfr
  - mpmath
  - nbclassic
  - nbconvert-pandoc
  - nbformat
  - nbmerge
  - nbstripout
  - nest-asyncio
  - netifaces
  - networkx
  - notebook
  - notebook-shim
  - numpy
  - numpy-base
  - openblas
  - openssl
  - pandas
  - pandoc
  - pango
  - parso
  - pcre
  - pillow
  - pip
  - prometheus_client
  - prompt_toolkit
  - protobuf
  - psutil
  - pycparser
  - pygments
  - pyjwt
  - pyopenssl
  - pyparsing
  - pyrsistent
  - pysocks
  - python
  - python-dateutil
  - python-graphviz
  - python-libarchive-c
  - python_abi
  - pytz
  - pyyaml
  - pyzmq
  - requests
  - ruamel_yaml
  - scikit-learn
  - scipy
  - seaborn
  - send2trash
  - setuptools
  - six
  - sniffio
  - soupsieve
  - sqlite
  - stack_data
  - sympy
  - tblib
  - terminado
  - text-unidecode
  - threadpoolctl
  - tk
  - tornado
  - traitlets
  - typing_extensions
  - tzdata
  - unicodedata2
  - urllib3
  - wcwidth
  - webencodings
  - wheel
  - widgetsnbextension
  - xz
  - yaml
  - zeromq
  - zipp
  - zlib
  - zstd
